version: "3.8"

services:
  flask-app:
    image: luciagruiz/flask-app:latest  # Usa el nombre de la imagen que creaste
    container_name: flask-app
    ports:
      - "5002:5002"  # Mapea el puerto del contenedor al host
    environment:
      - NOMBRE=$NOMBRE  # Define una variable de entorno
    volumes:
      - contador_data:/usr/share/app/contador.txt  # Mantiene el archivo contador.txt persistente
    restart: unless-stopped  # Reinicia el contenedor si falla

volumes:
  contador_data:
